
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: user-service-api
  description: A Spring Boot REST API for managing user accounts
  tags:
    - java
    - springboot
    - rest
    - api
  annotations:
    # Link to the GitHub repo
    source-location: url:https://github.com/vamsi585/temp_micro/tree/branch2/demo
  
spec:
  type: openapi
  lifecycle: experimental
  owner: team-user-platform
  system: identity-management
  definition: 
  openapi: 3.0.3
info:
  title: User Management API
  description: API for managing users in the system
  version: 1.0.0
 
servers:
  - url: http://localhost:8080/api
    description: Local development server
 
paths:
  /hello:
    get:
      summary: Get all users
      tags:
        - Users
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    


